name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
        # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.21.4' # The Go version to download (if necessary) and use.
    - run: go version

    - name: Build
      run: go build -o main main.go
      
    - name: Test
      run: go test -v ./...

    - name: Run
      run: ./main

    - name: List Distributions
      run: ls -allh
