name: Go

on:
  push:
    tags:
      - "v*"

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: golang:latest

    steps:
      - uses: actions/checkout@v4

      - name: build
        run: make all

      - name: Zip the binary
        run: zip -r gox.zip bin

      - uses: actions/checkout@v3
      - name: Create a release
        uses: action-pack/github-release@v2
        with:
          tag: MyReleaseTag
          title: MyReleaseTitle
          body: MyReleaseMessage