name: release

on:
  push:
    tags:
      - "v*"

jobs:
  container-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
      - run: go version
        with:
          go-version: '>=1.21.4'

      - name: build
        run: make all

      - name: Zip the binary
        run: sudo apt-get install zip && zip -r gox.zip bin

      - uses: actions/checkout@v3
      - name: Create a release
        uses: action-pack/github-release@v2
        with:
          tag: MyReleaseTag
          title: MyReleaseTitle
          body: MyReleaseMessage